id: P000499
initial_creation_type: ocr
source_metadata:
  id: bdr:W15588
  title: ཡན་ལག་བརྒྱད་པའི་སྙིང་པོ་བསྡུས་པ
  author: ''
  volumes:
    5b18a5204fd34fafb20a587baf00f780:
      image_group_id: I1PD382
      title: Volume 1 of yan lag brgyad pa'i snying po bsdus pa
      volume_number: 1
      total_pages: 528
      base_file: v001.txt
ebook_metadata:
  title: ཡན་ལག་བརྒྱད་པའི་སྙིང་པོ་བསྡུས་པ
  author: ''
  sku: P000499
  cover: cover.jpg
  layers:
  - pagination
